export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const SORT_PRODUCTS = "SORT_PRODUCTS";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export  const ADD_TO_CART = "ADD_TO_CART";
export  const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export  const DEC_CART_COUNT = "DEC_CART_COUNT";